version: '3'

services:
  nginx_urjc:
    image: neree00/nginxurjc:0.1
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html:/usr/share/nginx/html:ro
    container_name: nginxurjc_1
